complete -c wd -s a -l add -f -r -d "Add paths"
complete -c wd -s s -l ls -d "Run ls after warping"
complete -c wd -s r -l remove -f -r -d "Remove paths"
complete -c wd -l update -d "Update WarpDrive to the latest commit"
complete -c wd -s l -l list -d "List tracked dirs"
complete -c wd -s h -l help -d "Print a small help message"
